# Generated by Django 3.2 on 2024-01-25 12:53

import django.contrib.auth.validators
import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={"ordering": ("pk",)},
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    reviews.validators.validate_username,
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("title_id", "author"), name="unique_person"
            ),
        ),
    ]
