# Generated by Django 3.2 on 2024-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_remove_user_confirmation_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "default_related_name": "genres",
                "ordering": ("name",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
    ]
