# Generated by Django 3.2 on 2024-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240120_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.TextField(),
        ),
    ]
