# Generated by Django 3.2 on 2024-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_genre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("name",),
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                related_name="genres",
                through="reviews.GenreTitle",
                to="reviews.Genre",
                verbose_name="Жанр",
            ),
        ),
    ]
