# Generated by Django 3.2 on 2024-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_auto_20240201_1552"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_person",
        ),
        migrations.AlterField(
            model_name="title",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                through="reviews.GenreTitle",
                to="reviews.Genre",
                verbose_name="Жанр",
            ),
        ),
    ]
